
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
export const GET_BY_CATEGORY_SERVICES = 'GET_BY_CATEGORY_SERVICES';
export const FILTER_SERVICES = 'FILTER_SERVICES';
export const GET_SERVICE_BY_NAME = 'GET_SERVICE_BY_NAME';
export const MAKE_BOOKING = 'MAKE_BOOKING';